version: '3.8'

services:
    db:
        container_name: postgres
        image: postgres:17.4
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            # - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - '5433:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - stream-pipe-backend

volumes:
    postgres_data:

networks:
    stream-pipe-backend:
